AllCops:
  Exclude:
    - tapestry.gemspec
    - examples/*.rb
    - spec/**/*

# Removing need for frozen string literal comment.
#Style/FrozenStringLiteralComment:
#  Enabled: false

# Removing the preference for string single quotes.
Style/StringLiterals:
  Enabled: false

# Missing top-level module documentation comment.
Style/Documentation:
  Enabled: false

# Prefer reduce over inject.
Style/CollectionMethods:
  PreferredMethods:
    reduce: 'inject'

# Use each_with_object instead of inject.
Style/EachWithObject:
  Enabled: false

# Prefer fail over raise.
Style/SignalException:
  Enabled: false

# This never works for validations.
Style/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

# Align multi-line params with previous line.
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# Indent `when` clause one step from `case`.
Style/CaseIndentation:
  IndentOneStep: true

# Don't force bad var names for reduce/inject loops.
Style/SingleLineBlockParams:
  Enabled: false

# For method chains, keep the dot with the method name.
Style/DotPosition:
  EnforcedStyle: leading

# Stop nesting so hard.
Metrics/BlockNesting:
  Max: 2

# Encourage short methods.
Metrics/MethodLength:
  Max: 15

# Encourage fewer parameters.
Metrics/ParameterLists:
  Max: 4

# Allow methods with has_ for predicates.
Style/PredicateName:
  NameWhitelist:
    - has_correct_url?
    - has_correct_title?
